config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/new'
  resources :books, only: %i[create new index]
  resources :members, only: %i[create new index]
  resources :book_rentals, only: %i[create new index]
  resources :returns, only: %i[create new]
  resources :member_book_rentals, only: %i[index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  include PgSearch::Model
  include Filterable

  belongs_to :author
  belongs_to :publisher, optional: true
  has_many :book_categories
  has_many :categories, through: :book_categories
  has_many :book_rentals

  attr_accessor :category_names

  validates :name, presence: true
  validates :publishing_year, numericality: { allow_nil: true, less_than_or_equal_to: Time.now.year }
  validates :author_id, presence: true

  pg_search_scope :search_by_name,
                  against: %i[name],
                  associated_against: {
                    author: :name
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  # acts like a scope
  def self.available
    where.not(id: joins(:book_rentals).where(book_rentals: { returned_on: nil }))
  end

  def self.unavailable
    where(id: joins(:book_rentals).where(book_rentals: { returned_on: nil }))
  end

  def self.filter_by_availability(availability)
    case availability
    when 'true', true
      available
    when 'false', false
      unavailable
    else
      all
    end
  end

  def self.search_by_id(search_id)
    where(id: search_id)
  end

  def self.search(query, max_results=nil)
    if /^\d+$/.match(query.to_s)
      search_by_id(query).limit(max_results)
    elsif query.present?
      search_by_name(query).limit(max_results)
    else
      all.limit(max_results)
    end
  end

  def self.create_with_associated_models(hash = {})
    Book.transaction do
      author = Author.find_or_create_by(name: hash[:author_name])
      publisher = Publisher.find_or_create_by(name: hash[:publisher_name])
      categories = hash[:category_names]&.split(',')&.map do |category_name|
        Category.find_or_create_by(name: category_name.strip)
      end || []
      @new_book = Book.create(name: hash[:name], author: author, publisher: publisher,
                              publishing_year: hash[:publishing_year], categories: categories)
      raise ActiveRecord::Rollback if @new_book.invalid?

    end
    @new_book
  end

  def available?
    !BookRental.exists?(book_id: id, returned_on: nil)
  end
end

app/controllers/member_book_rentals_controller.rb
class MemberBookRentalsController < ApplicationController
  def index
    @member_book_rentals = BookRental.current.includes(:book).where(member_id: member_book_rentals_params[:member_id])
    @returning_on = returning_on
    respond_to do |format|
      format.html { render partial: 'member_book_rentals' }
      format.json { render json: @member_book_rentals }
    end
  end

  private

  def returning_on
    member_book_rentals_params[:returning_on]&.to_date
  rescue Date::Error => e
    Date.today
  end

  def member_book_rentals_params
    params.permit(:member_id, :returning_on)
  end
end

app/helpers/member_book_rentals_helper.rb
module MemberBookRentalsHelper
end

app/views/member_book_rentals/_member_book_rentals.html.erb
<% if @member_book_rentals.length > 0 %>
  <div class="overflow-x-auto w-full">
    <table class="index-table">
      <thead>
      <tr>
        <th></th>
        <th><%= t('activerecord.attributes.book.id') %></th>
        <th><%= t('activerecord.attributes.book.name') %></th>
        <th><%= t('activerecord.attributes.book_rental.issued_on') %></th>
        <th><%= t('activerecord.attributes.book_rental.due_by') %></th>
        <th><%= t('activerecord.attributes.book_rental.fine') %></th>
      </tr>
      </thead>
      <tbody>
      <% @member_book_rentals.each do |book_rental| %>
        <tr data-controller="book-rental-return" data-action="changed->returns-form#handleFineChange">
          <td>
            <%= check_box :return, :book_rental_ids, {multiple: true, data: { action: "book-rental-return#handleChecked" }}, book_rental.id, nil %>
          </td>
          <td><%= book_rental.book.id %></td>
          <td><%= book_rental.book.name %></td>
          <td><%= book_rental.issued_on %></td>
          <td><%= book_rental.due_by %></td>
          <td class="pr-4">
            &#8377; <span data-book-rental-return-target="fine"><%= "#{'%.2f' % book_rental.fine(@returning_on)}" %></span>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="flex w-full justify-center items-center">
    <p class="font-light text-gray-400 italic"><%= t('no_books_available') %></p>
  </div>
<% end %>