config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/new'
  resources :books, only: %i[create new index]
  resources :members, only: %i[create new index]
  resources :book_rentals, only: %i[create new index]
  resources :returns, only: %i[create new]
  resources :member_book_rentals, only: %i[index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/shared/_form_error_messages.html.erb
<% flash.each do |flash_type, flash_content| %>
  <% if flash_type == 'form_errors' && flash_content.respond_to?('each') %>
    <div class="bg-red-100 p-3 pl-8 mb-4 rounded-md font-bold text-red-700 border border-red-500 text-left">
      <% flash_content.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  <% elsif flash_type == 'form_error' %>
    <div class="bg-red-100 p-3 mb-4 rounded-md font-bold text-red-700 border border-red-500 text-center">
      <%= flash_content %>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="w-full px-4 md:px-12 py-4 shadow-md">
  <div class="flex justify-between items-center">
    <%= link_to t('library_name'), root_path, class: "font-black text-3xl text-blue-500" %>
    <nav class="flex flex-row items-center">
      <% if logged_in? %>
        <div class="group relative inline-block ml-8 py-2">
          <div>
            <button type="button" class="text-md font-semibold inline-flex justify-center items-center" aria-expanded="true" aria-haspopup="true">
              <%= link_to t('rentals'), book_rentals_path %>
              <svg class="-mr-1 ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
          </div>
          <div class="mt-2 hidden group-hover:block origin-top-right absolute right-0 min-w-24 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
            <div class="py-1 text-center" role="none">
              <%= link_to t('all'), book_rentals_path, class: "text-gray-700 block px-4 py-2 hover:bg-gray-300" %>
              <%= link_to t('new'), new_book_rental_path, class: "text-gray-700 block px-4 py-2 hover:bg-gray-300" %>
            </div>
          </div>
        </div>
        <div class="group relative inline-block ml-8 py-2">
          <div>
            <button type="button" class="text-md font-semibold inline-flex justify-center items-center" aria-expanded="true" aria-haspopup="true">
              <%= link_to t('new_return'), new_return_path %>
            </button>
          </div>
        </div>
        <div class="group relative inline-block ml-8 py-2">
          <div>
            <button type="button" class="text-md font-semibold inline-flex justify-center items-center" aria-expanded="true" aria-haspopup="true">
              <%= link_to t('books'), books_path %>
              <svg class="-mr-1 ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
          </div>
          <div class="mt-2 hidden group-hover:block origin-top-right absolute right-0 min-w-24 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
            <div class="py-1 text-center" role="none">
              <%= link_to t('all'), books_path, class: "text-gray-700 block px-4 py-2 hover:bg-gray-300" %>
              <%= link_to t('new'), new_book_path, class: "text-gray-700 block px-4 py-2 hover:bg-gray-300" %>
            </div>
          </div>
        </div>
        <div class="group relative inline-block ml-8 py-2">
          <div>
            <button type="button" class="text-md font-semibold inline-flex justify-center items-center" aria-expanded="true" aria-haspopup="true">
              <%= link_to t('members'), members_path %>
              <svg class="-mr-1 ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
          </div>
          <div class="mt-2 hidden group-hover:block origin-top-right absolute right-0 min-w-24 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
            <div class="py-1 text-center" role="none">
              <%= link_to t('all'), members_path, class: "text-gray-700 block px-4 py-2 hover:bg-gray-300" %>
              <%= link_to t('new'), new_member_path, class: "text-gray-700 block px-4 py-2 hover:bg-gray-300" %>
            </div>
          </div>
        </div>
        <div class="ml-8 pr-4 h-10 drop-shadow-md flex justify-center items-center text-md text-blue-500 border rounded-full bg-blue-100 font-semibold">
          <div class="mr-2 h-5 w-5 bg-blue-600 rounded-full font-black text-white flex justify-center items-center p-5">
            <%= current_staff&.username.to_s.first.capitalize %>
          </div>
          <div>
            <%= link_to t('log_out'), logout_path, method: :delete, class: "text-md font-semibold" %>
          </div>
        </div>
      <% else %>
        <%= link_to t('log_in'), login_path, class: "ml-8 text-md font-semibold" %>
      <% end %>
    </nav>
  </div>
</div>

app/views/shared/_pagination_bar.html.erb
<div class="mt-6">
  <% link = pagy_link_proc(pagy) -%>
  <nav aria-label="pager" class="pagy_nav pagination" role="navigation">
    <% if pagy.prev -%>
      <span class="page p-2 prev font-semibold rounded-md"><%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></span>
    <% else -%>  <span class="page p-2 font-semibold prev disabled text-gray-400 rounded-md"><%== pagy_t('pagy.nav.prev') %></span>
    <% end -%>
    <% pagy.series.each do |item|
      # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]  -%>
      <% if item.is_a?(Integer) -%>  <span class="page py-2 px-3 font-semibold hover:border hover:border-blue-500 rounded-md"><%== link.call(item) %></span>
      <% elsif item.is_a?(String) -%>  <span class="page p-2 px-3 font-bold bg-blue-500 text-white current rounded-md"><%= item %></span>
      <% elsif item == :gap -%>  <span class="page p-2 px-3 font-semibold gap rounded-md"><%== pagy_t('pagy.nav.gap') %></span>
      <% end -%>
    <% end -%>
    <% if pagy.next -%>
      <span class="page p-2 font-semibold next rounded-md hover:border hover:border-blue-500"><%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></span>
    <% else -%>  <span class="page p-2 font-semibold next disabled text-gray-400 rounded-md"><%== pagy_t('pagy.nav.next') %></span>
    <% end -%>
  </nav>
</div>

app/views/shared/_snackbar.html.erb
<div class="py-4 px-8 mb-4 text-md bg-green-100 rounded-md border border-green-500 text-green-900 font-semibold text-center">
  <%= message %>
</div>

app/views/shared/_snackbar_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'snack_success' %>
    <%= render "shared/snackbar", message: message %>
  <% end %>
<% end %>